# Generated by rolit-cli's release workflow. Do not edit by hand.
class Rolit < Formula
  desc "Native client for Rolit's hosted agent runtime"
  homepage "https://github.com/recnos-in/rolit-cli-releases"
  version "0.1.2"

  on_macos do
    on_arm do
      url "https://github.com/recnos-in/rolit-cli-releases/releases/download/v0.1.2/rolit-aarch64-apple-darwin.tar.gz"
      sha256 "134ffac784644a25cc269e44ac2ac99d4f455776e2f0add09804cf3d1f1a2b17"
    end
    on_intel do
      url "https://github.com/recnos-in/rolit-cli-releases/releases/download/v0.1.2/rolit-x86_64-apple-darwin.tar.gz"
      sha256 "bb6b86be8ab65cda8ed17314cc9eabd4d0ada58a2b5bedc774d567f875b017aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/recnos-in/rolit-cli-releases/releases/download/v0.1.2/rolit-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "25bd6818f2e4aede871ccee1f0fd99cd665aec17ec1d0a3b12922106331a0bf6"
    end
    depends_on "alsa-lib"
    depends_on "libxcb"
  end

  def install
    bin.install "rolit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rolit --version")
  end
end
